package gestemployee;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Vector;

import static java.awt.event.WindowEvent.WINDOW_DEACTIVATED;
import static java.awt.event.WindowEvent.WINDOW_LOST_FOCUS;
import static javax.swing.JOptionPane.ERROR_MESSAGE;

public class FormEmployee extends JFrame {
    private JPanel panel1;
    private JTextField tfCoporateKey;
    private JButton addEmployee;
    private JTextField tfName;
    private JTextField tfSquad;
    private JTextField tfEmail;
    private JTextField tfTribe;
    private final String tFieldsTitle[] = {"Corp key", "Name", "eMail", "Squad", "Tribe"};
    private String sSheetName = "Employee Detail";
    ExcelFile oEF;
    private boolean bEdit = true;
    //private boolean bGained = false;

    //Set<Map.Entry<String, String>>
    // receive input from user
    public ArrayList<String> getEmployeDetail() {
        //private ArrayList<String> alField = new ArrayList<String>(Arrays.asList());
        ArrayList<String> oL = new ArrayList<String>(Arrays.asList(
                tfCoporateKey.getText(),
                tfName.getText(),
                tfEmail.getText(),
                tfSquad.getText(),
                tfTribe.getText()
        ));

        return oL;
    }

    @Override
    protected void processWindowEvent(WindowEvent e) {
        System.out.println("processWindowEvent " + e.getID() + "=" + WINDOW_LOST_FOCUS);
        if (e.getID() == WINDOW_LOST_FOCUS || e.getID() == WINDOW_DEACTIVATED) {

            if (bEdit == false) {
                System.out.println("processWindowEvent 2");
                this.dispose();
            }
        }
        super.processWindowEvent(e);
    }

    FormEmployee(String pFileName) {
        super("Enter Employee Data");
        final String inputFilePath = pFileName;//System.getProperty("user.dir") + "/src/resources/" + "Employee.xlsx";

        if (oEF == null) {
            oEF = new ExcelFile(inputFilePath, sSheetName, new ArrayList<String>(Arrays.asList(tFieldsTitle)));
        }
        setContentPane(panel1);
        setBounds(200, 200, 500, 300);
        //setDefaultCloseOperation(EXIT_ON_CLOSE);
        //JFrame frame = new JFrame();
        setVisible(true);

        addEmployee.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                //setVisible(false);

                System.out.println("add button");

                if (tfCoporateKey.getText().isEmpty() || tfCoporateKey.getText().trim().equals("")) {
                    JOptionPane.showMessageDialog(null, "Corporate Key Empty", tfCoporateKey.getText(), ERROR_MESSAGE);
                } else if (oEF.checkIfExist(tfCoporateKey.getText())) {
                    JOptionPane.showMessageDialog(null, "Already Exist", tfCoporateKey.getText(), ERROR_MESSAGE);
                } else {
                    if (tfCoporateKey.getText().isEmpty() || tfCoporateKey.getText().equals(""))
                        tfCoporateKey.setText(" ");
                    if (tfName.getText().isEmpty() || tfName.getText().equals("")) tfName.setText(" ");
                    if (tfEmail.getText().isEmpty() || tfEmail.getText().equals("")) tfEmail.setText(" ");
                    if (tfSquad.getText().isEmpty() || tfSquad.getText().equals("")) tfSquad.setText(" ");
                    if (tfTribe.getText().isEmpty() || tfTribe.getText().equals("")) tfTribe.setText(" ");
                    oEF.writeToExcel(sSheetName, getEmployeDetail());
                }
            }

        });


        addEmployee.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });
    }

    FormEmployee(Vector<String> pEmployee) {
        super("Display Employee");
        this.bEdit = false;
        setContentPane(panel1);
        setBounds(200, 200, 500, 300);
        //setDefaultCloseOperation(EXIT_ON_CLOSE);
        //JFrame frame = new JFrame();
        tfCoporateKey.setText(pEmployee.get(0));
        tfCoporateKey.setEditable(false);
        tfName.setText(pEmployee.get(1));
        tfName.setEditable(false);
        tfEmail.setText(pEmployee.get(2));
        tfEmail.setEditable(false);
        tfSquad.setText(pEmployee.get(3));
        tfSquad.setEditable(false);
        tfTribe.setText(pEmployee.get(4));
        tfTribe.setEditable(false);
        setVisible(true);
        addEmployee.setVisible(false);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new FormLayout("fill:378px:grow,left:150dlu:noGrow", "center:d:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        final JLabel label1 = new JLabel();
        label1.setHorizontalAlignment(0);
        label1.setHorizontalTextPosition(0);
        label1.setText("Employee");
        CellConstraints cc = new CellConstraints();
        panel1.add(label1, cc.xy(1, 1));
        final JLabel label2 = new JLabel();
        label2.setAlignmentY(0.5f);
        label2.setHorizontalTextPosition(2);
        label2.setMaximumSize(new Dimension(20, 30));
        label2.setMinimumSize(new Dimension(20, 20));
        label2.setPreferredSize(new Dimension(10, 38));
        label2.setText("CorporateKey");
        panel1.add(label2, cc.xy(1, 3, CellConstraints.DEFAULT, CellConstraints.TOP));
        tfCoporateKey = new JTextField();
        tfCoporateKey.setText("");
        panel1.add(tfCoporateKey, cc.xy(2, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        tfName = new JTextField();
        tfName.setText("");
        panel1.add(tfName, cc.xy(2, 5, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JLabel label3 = new JLabel();
        label3.setAlignmentY(0.5f);
        label3.setHorizontalTextPosition(2);
        label3.setMaximumSize(new Dimension(20, 30));
        label3.setMinimumSize(new Dimension(20, 20));
        label3.setPreferredSize(new Dimension(10, 38));
        label3.setText("Name");
        panel1.add(label3, cc.xy(1, 5, CellConstraints.DEFAULT, CellConstraints.TOP));
        final JLabel label4 = new JLabel();
        label4.setAlignmentY(0.5f);
        label4.setHorizontalTextPosition(2);
        label4.setMaximumSize(new Dimension(20, 30));
        label4.setMinimumSize(new Dimension(20, 20));
        label4.setPreferredSize(new Dimension(10, 38));
        label4.setText("eMail");
        panel1.add(label4, cc.xy(1, 7, CellConstraints.DEFAULT, CellConstraints.TOP));
        final JLabel label5 = new JLabel();
        label5.setAlignmentY(0.5f);
        label5.setHorizontalTextPosition(2);
        label5.setMaximumSize(new Dimension(20, 30));
        label5.setMinimumSize(new Dimension(20, 20));
        label5.setPreferredSize(new Dimension(10, 38));
        label5.setText("sQuad");
        panel1.add(label5, cc.xy(1, 9, CellConstraints.DEFAULT, CellConstraints.TOP));
        final JLabel label6 = new JLabel();
        label6.setAlignmentY(0.5f);
        label6.setHorizontalTextPosition(2);
        label6.setMaximumSize(new Dimension(20, 30));
        label6.setMinimumSize(new Dimension(20, 20));
        label6.setPreferredSize(new Dimension(10, 38));
        label6.setText("Tribe");
        panel1.add(label6, cc.xy(1, 11, CellConstraints.DEFAULT, CellConstraints.TOP));
        addEmployee = new JButton();
        addEmployee.setText("Button");
        panel1.add(addEmployee, cc.xy(2, 13));
        tfEmail = new JTextField();
        tfEmail.setText("");
        panel1.add(tfEmail, cc.xy(2, 7, CellConstraints.FILL, CellConstraints.DEFAULT));
        tfSquad = new JTextField();
        tfSquad.setText("");
        panel1.add(tfSquad, cc.xy(2, 9, CellConstraints.FILL, CellConstraints.DEFAULT));
        tfTribe = new JTextField();
        tfTribe.setText("");
        panel1.add(tfTribe, cc.xy(2, 11, CellConstraints.FILL, CellConstraints.DEFAULT));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
    //void run() {
    // setContentPane(new FormEmployee().panel1);
    // setBounds(200, 200, 500, 300);
    //setDefaultCloseOperation(EXIT_ON_CLOSE);
    //JFrame frame = new JFrame();
    //setVisible(true);
    //}

}
