package javatraining.gui;

import javax.swing.*;
import java.awt.*;
import com.intellij.*;

public class Table {
    private JTable table;
    private JComboBox comboBox1;
    private JTextField textField1;
    private JTextPane textPane1;

    public Table(String rowsData[][], String column[]) {

        JFrame frame = new JFrame();

        table = new JTable(rowsData, column);


        table.setBounds(30, 40, 200, 300);
        table.setBackground(Color.CYAN);

        JScrollPane scrollPane = new JScrollPane(table);

        frame.add(scrollPane);

        frame.setSize(400, 400);
        frame.setVisible(true);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);


    }

    public static void main(String[] args) {


        String rowsData[][] = {

                {"AAA101", "Ben", "Expression", "DOCUMENTUM"},
                {"102", "Chitra", "Expression", "DOCUMENTUM"},
                {"103", "Seba", "Data Mover", "CIM"},
                {"101", "Ben", "Expression", "DOCUMENTUM"},
                {"102", "Chitra", "Expression", "DOCUMENTUM"},
                {"103", "Seba", "Data Mover", "CIM"},
                {"101", "Ben", "Expression", "DOCUMENTUM"},
                {"102", "Chitra", "Expression", "DOCUMENTUM"},
                {"103", "Seba", "Data Mover", "CIM"},
                {"101", "Ben", "Expression", "DOCUMENTUM"},
                {"102", "Chitra", "Expression", "DOCUMENTUM"},
                {"103", "Seba", "Data Mover", "CIM"}, {"101", "Ben", "Expression", "DOCUMENTUM"},
                {"102", "Chitra", "Expression", "DOCUMENTUM"},
                {"103", "Seba", "Data Mover", "CIM"},
                {"101", "Ben", "Expression", "DOCUMENTUM"},
                {"102", "Chitra", "Expression", "DOCUMENTUM"},
                {"103", "Seba", "Data Mover", "CIM"},
                {"101", "Ben", "Expression", "DOCUMENTUM"},
                {"102", "Chitra", "Expression", "DOCUMENTUM"},
                {"103", "Seba", "Data Mover", "CIM"},
                {"101", "Ben", "Expression", "DOCUMENTUM"},
                {"102", "Chitra", "Expression", "DOCUMENTUM"},
                {"103", "Seba", "Data Mover", "CIM"},
                {"101", "Ben", "Expression", "DOCUMENTUM"},
                {"102", "Chitra", "Expression", "DOCUMENTUM"},
                {"103", "Seba", "Data Mover", "CIM"},
                {"101", "Ben", "Expression", "DOCUMENTUM"},
                {"102", "Chitra", "Expression", "DOCUMENTUM"},
                {"103", "Seba", "Data Mover", "CIM"},
                {"101", "Ben", "Expression", "DOCUMENTUM"},
                {"102", "Chitra", "Expression", "DOCUMENTUM"},
                {"103", "Seba", "Data Mover", "CIM"}, {"101", "Ben", "Expression", "DOCUMENTUM"},
                {"102", "Chitra", "Expression", "DOCUMENTUM"},
                {"103", "Seba", "Data Mover", "CIM"},


                {"104", "Nishit", "Expression", "DOCUMENTUM"}
        };

        String column[] = {"CORP KEY", "NAME", "SQUAD", "TRIBE"};

        Table table = new Table(rowsData, column);

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(5, 2, new Insets(0, 0, 0, 0), -1, -1));
        table = new JTable();
        panel1.add(table, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 1, false));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        panel1.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(3, 1, 2, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        comboBox1 = new JComboBox();
        panel1.add(comboBox1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        textField1 = new JTextField();
        panel1.add(textField1, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Label");
        panel1.add(label1, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        textPane1 = new JTextPane();
        panel1.add(textPane1, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
    }
}
